#!/bin/bash

sudo su
yum -y install rpm-build make gcc git 
mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
cd ~
cd rpmbuild/SOURCES

git clone https://github.com/nic-instruction/NTI-320
cd /NTI-320/rpm-info
mv helloworld-0.1.tar.gz ../../helloworld-0.1.tar.gz

cd ../../../SPECS
wget https://raw.githubusercontent.com/nic-instruction/NTI-320/master/rpm-info/exampe-specs/hello.spec

cd .. 
rpmbuild -v -bb --clean SPECS/nagios.spec
